### PR TITLE
[#169] Complex and simple reward generation

### LINKED ISSUE #169: Complex and simple reward generation
Implement mechanism of choosing complex or simple reward generation.

### PR DESCRIPTION
**Pull request by wujuu**
Closes #169

### CODE REVIEW

**Review by JanKapala — CHANGES_REQUESTED** [review]
Maybe "simple", "complex" default strings could be replaced with constants, enums or named tuples?

**Comment by JanKapala** [comment]
> I thought about it, but then I remebered that a lot of state of the art frameworks do it this way (for example pandas DataFrame.plot(kind="scatter")).

Maybe they have some reasons for doing it in this way, but if you would like to change string from "simple" to "plain" you would have to do it in all places. Moreover if there will be more kinds of reward in the future it would be a mess to maintain all these strings. Well defined constants/enums/named-tuples are better in our case and follow open close principle.

**Comment by wujuu** [comment]
> > I thought about it, but then I remebered that a lot of state of the art frameworks do it this way (for example pandas DataFrame.plot(kind="scatter")).
> 
> They may have some reason to do it this way, but if you wanted to change a string from "simple" to "plain" you would have to do it in all places. Furthermore, if there are more types of rewards in the future, keeping all those strings would be a mess. Well defined constants/enums/named-tuples are better in our case and follow the open close principle.

You still need to search for all places where the enum is and change it to Mode.Plain though

**Comment by JanKapala** [comment]
> > > I thought about it, but then I remebered that a lot of state of the art frameworks do it this way (for example pandas DataFrame.plot(kind="scatter")).
> > 
> > 
> > They may have some reason to do it this way, but if you wanted to change a string from "simple" to "plain" you would have to do it in all places. Furthermore, if there are more types of rewards in the future, keeping all those strings would be a mess. Well defined constants/enums/named-tuples are better in our case and follow the open close principle.
> 
> You still need to search for all places where the enum is and change it to Mode.Plain though

but you don't need to worry about typos in strings while typos in constant names are checked by the pycharm. Literal strings used as enums are generally bad idea.

**Review by JanKapala — APPROVED** [review]

**Pull request merged**
