### PR TITLE
[#404] Adjust user actions

### LINKED ISSUE #404: Adjust user_actions
SS:
https://eosc-search-service.grid.cyfronet.pl/
```
    JMS_HOST = 'beta.providers.eosc-portal.eu'
    JMS_HOST = 'sandbox.providers.eosc-portal.eu'
    JMS_PORT = 61613
    TOPIC_UA = "/topic/user_actions"
```

User_actions will be added to SS and UD.

Adjust user actions handling to the new user action schema:
- Use only user actions that have `client_id == "marketplace"`.
- Drop not-service resources.
- From now `resource_id` and `resource_type` will be always present in the user action's root. (`resource_id` and `resource_type`  are NOT required fields, they should be treated as optional).

[PR](https://github.com/cyfronet-fid/eosc-search-service/pull/192) in which UA are added to SS

### PR DESCRIPTION
**Pull request by JanKapala**
Closes #404

### CODE REVIEW

**Review by wujuu — COMMENTED** [review]
lgtm

**Review by wujuu — APPROVED** [review]
lgtm

**Review by Michal-Kolomanski — COMMENTED** [review]
The code looks good, but we cannot merge this before merging https://github.com/cyfronet-fid/marketplace/pull/2780. Set up locally MP and recommender and please test this

**Comment by wujuu** [comment]
Adjusted database dump to only intake fields that are defined in the model on the recommender side

**Pull request merged**
